version: 2
jobs:
  build_and_test:
    working_directory: ~/auth0-dbscripts
    docker:
      - image: circleci/node:4.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Jest tests
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
